config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_DOCKERFORCEPUSH: enabled
sqa_criteria:
  QC.Sty:
    repos:
      this_repo:
        commands:
        - hadolint worker-image/Dockerfile --ignore SC2046 --ignore DL3059 --ignore
          SC2086 --ignore DL3008
        container: qc.sty_droopy-linen-fish
timeout: 600
